/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthLayout: typeof import('./src/components/layouts/AuthLayout.vue')['default']
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseCheckbox: typeof import('./src/components/base/BaseCheckbox.vue')['default']
    BaseDialog: typeof import('./src/components/base/BaseDialog.vue')['default']
    BaseLabelBar: typeof import('./src/components/base/BaseLabelBar.vue')['default']
    BaseNotice: typeof import('./src/components/base/BaseNotice.vue')['default']
    BaseRadioButtons: typeof import('./src/components/base/BaseRadioButtons.vue')['default']
    BaseTextfield: typeof import('./src/components/base/BaseTextfield.vue')['default']
    BaseTitle: typeof import('./src/components/base/BaseTitle.vue')['default']
    PortalLayout: typeof import('./src/components/layouts/PortalLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
  }
}
